"""empty message

Revision ID: c215693dd4dc
Revises: 145e1010cf47
Create Date: 2022-10-05 12:30:00.068519

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c215693dd4dc"
down_revision = "145e1010cf47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
